# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

ARCHITECTURE     = avr
BOARD_TAG        = nano
BOARD_SUB        = atmega328
ISP_PORT     		 = /dev/tty.wchusbserial1420

MONITOR_CMD      = picocom
MONITOR_BAUDRATE = 115200
MONITOR_PARAMS   = --omap crcrlf
# MONITOR_PORT     = /dev/tty.usbserial

include /Users/biesiad/Projects/Arduino-Makefile/Arduino.mk
